#!/bin/bash

while getopts "l" opt; do
  case $opt in
    l)
      rofi -show run -lines 6 -width 500 -bw 2 -sidebar-mode -color-enabled -color-window '#2E2F33,#A2A7B5,#2E2F33' -color-normal '#2E2F33,#CAC9C6,#2E2F33,#2E2F33,#A2A7B5'  -color-active '#2E2F33,#F7B646,#2E2F33,#2E2F33,#F7B646' -separator-style solid -padding 25
      ;;
  esac
done


