#!/bin/sh

# program-specific desktops to create at startup
desktops='slack digikam'

# create startup desktops
bspc monitor -d home $desktops

# set program-specific startup desktops to monocle mode
for d in $desktops; do
    bspc desktop $d --layout monocle
done


bspc config border_width 2
bspc config window_gap 10

# monocle mode settings
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config borderless_monocle true

bspc rule -a Slack    desktop=slack follow=on
bspc rule -a digikam  desktop=digikam follow=on
bspc rule -a Pinentry desktop=focused state=floating
