api_server_host: http://evergreen.mongodb.com/api
ui_server_host: https://evergreen.mongodb.com
api_key: 
user: ryan.chipman
projects:
- name: mongosql-auth-c
  default: false
  variants:
  - full_matrix__os~windows-32
  - full_matrix__os~windows-vs2013
  - full_matrix__os~osx
  - full_matrix__os~ubuntu1404-64
  - full_matrix__os~rhel70
  tasks:
  - all
- name: sqlproxy
  default: true
  variants:
  - full_matrix__os_full_matrix~osx_mongodb_version~latest_mongodb_topology~standalone
  - full_matrix__os_full_matrix~windows_mongodb_version~latest_mongodb_topology~standalone
  - full_matrix__os_full_matrix~ubuntu1404-64_mongodb_version~latest_mongodb_topology~standalone
  tasks:
  - all
