#!/bin/bash

# this is a simple config for herbstluftwm

#hc() {
#    cmds="$cmds, $@"
#}

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# load keybindings
. ~/.config/herbstluftwm/keybinds

# load theme
. ~/.config/herbstluftwm/theme


# load rules
. ~/.config/herbstluftwm/rules

hc set auto_detect_monitors 1

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# execute all the above hc commands at once asynchronously
#herbstclient chain $cmds &
