#!/bin/bash

# this is a simple config for herbstluftwm

#hc() {
#    cmds="$cmds, $@"
#}

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

hc keybind $Mod-w close_or_remove
hc keybind $Mod-Return spawn lxterminal
hc keybind Control-Tab spawn launcher -l

## basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Control-h     shift left
hc keybind $Mod-Control-j     shift down
hc keybind $Mod-Control-k     shift up
hc keybind $Mod-Control-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-comma   split   bottom  0.5
hc keybind $Mod-period  split   right   0.5
hc keybind $Mod-space   split   explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Shift-h       resize left +$resizestep
hc keybind $Mod-Shift-j       resize down +$resizestep
hc keybind $Mod-Shift-k       resize up +$resizestep
hc keybind $Mod-Shift-l       resize right +$resizestep
hc keybind $Mod-Shift-Left    resize left +$resizestep
hc keybind $Mod-Shift-Down    resize down +$resizestep
hc keybind $Mod-Shift-Up      resize up +$resizestep
hc keybind $Mod-Shift-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-o use_index +1 --skip-visible
hc keybind $Mod-i  use_index -1 --skip-visible

hc keybind $Mod-Control-o chain :: move_index +1 --skip-visible :: use_index +1 --skip-visible
hc keybind $Mod-Control-i chain :: move_index -1 --skip-visible :: use_index -1 --skip-visible

# layouting
hc keybind $Mod-Control-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize

hc keybind F2 spawn sudo backlight.sh -d 300
hc keybind F3 spawn sudo backlight.sh -i 300

hc keybind XF86AudioLowerVolume spawn volume.sh -d 5
hc keybind XF86AudioRaiseVolume spawn volume.sh -i 5
hc keybind XF86AudioMute spawn volume.sh -m

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# no frame border
hc set frame_border_width 0
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#222222'

hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#33bb55'
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc set frame_active_opacity 0
hc set frame_normal_opacity 0

hc attr theme.active.color '#33bb55'
hc attr theme.normal.color '#565656'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 5
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#565656'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set auto_detect_monitors 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# execute all the above hc commands at once asynchronously
#herbstclient chain $cmds &
